# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/the_zen_of/',
                'doc_host': 'https://sizhky.github.io',
                'git_url': 'https://github.com/sizhky/https://github.com/sizhky/the-zen-of/',
                'lib_path': 'the_zen_of'},
  'syms': { 'the_zen_of.cpp': {'the_zen_of.cpp.cpp': ('cpp.html#cpp', 'the_zen_of/cpp.py')},
            'the_zen_of.javascript': {'the_zen_of.javascript.javascript': ('javascript.html#javascript', 'the_zen_of/javascript.py')},
            'the_zen_of.python': {'the_zen_of.python.python': ('python.html#python', 'the_zen_of/python.py')},
            'the_zen_of.setup': {}}}
