# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_cpp.ipynb.

# %% auto 0
__all__ = ['cpp']

# %% ../nbs/03_cpp.ipynb 3
from .setup import cli

# %% ../nbs/03_cpp.ipynb 4
@cli.command()
def cpp():
    info = '''Zen of CPP by ISOCPP
P.1: Express ideas directly in code
P.2: Write in ISO Standard C++
P.3: Express intent
P.4: Ideally, a program should be statically type safe
P.5: Prefer compile-time checking to run-time checking
P.6: What cannot be checked at compile time should be checkable at run time
P.7: Catch run-time errors early
P.8: Don't leak any resources
P.9: Don't waste time or space
P.10: Prefer immutable data to mutable data
P.11: Encapsulate messy constructs, rather than spreading through the code
P.12: Use supporting tools as appropriate
P.13: Use support libraries as appropriate

https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#S-philosophy
'''
    print(info)
