# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_python.ipynb.

# %% auto 0
__all__ = ['python']

# %% ../nbs/01_python.ipynb 2
from .setup import cli

# %% ../nbs/01_python.ipynb 3
@cli.command()
def python(): import this
