# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_setup.ipynb.

# %% auto 0
__all__ = ['cli', 'cli2', 'default', 'of', 'available']

# %% ../nbs/00_setup.ipynb 2
from typer import Typer, Context

# %% ../nbs/00_setup.ipynb 3
cli = Typer()

cli2 = Typer()
    
@cli2.callback()
def default(ctx: Context):
    ...

@cli2.command()
def of(lang):
    funcs = {c.__dict__['callback'].__name__:c.__dict__['callback'] for c in cli.registered_commands}
    return funcs[lang]()

@cli2.command()
def available():
    funcs = {c.__dict__['callback'].__name__:c.__dict__['callback'] for c in cli.registered_commands}
    print('-'+'\n-'.join(list(funcs.keys())))
